### ISSUE TITLE
Use filemanager as standalone

### ISSUE THREAD

**Issue by DenisAlliswell** [xvs32x/tinymce-responsivefilemanager#1]
Hi!

Thanks for sharing this widget!

Please advice how wrap filemanager plugin as stand-alone in Yii2 widget?

Many thanks in advance!

**Comment by xvs32x** [comment]
Without TinyMce?

**Comment by DenisAlliswell** [comment]
@xvs32x yes, as stand-alone link to load images via filemanager.

**Comment by xvs32x** [comment]
@DenisAlliswell now it's impossible. but I think about it
